//! Deterministic documents (ddocs): the row model flowspace3 indexes.
//!
//! A *deterministic document* is a `*.dd.json` file: structured data under a
//! declared schema, where every list row carries a permanent id. Beside it sits
//! a GENERATED `*.dd.md` sibling that can be arbitrarily stale with nothing
//! in-file saying so — which is why the source is the only thing we index.
//!
//! This module is the frozen contract every ddoc unit codes against. It is
//! pure: no I/O, no process spawning, no schema resolution. Anything needing
//! the world (resolving a schema, fetching the corpus edge graph) happens in
//! the imperative shell and arrives here as a value.
//!
//! Three rules are load-bearing, all measured by dd's own maintainer against
//! dd `main` `a53b79d` on 2026-08-28, and all easy to get wrong:
//!
//! * **The chunk is the ROW**, never the section and never the document. An
//!   element earns an id when it carries state or is a link target, and the
//!   row is the granularity a question like "which acceptance criterion covers
//!   X" actually wants.
//! * **Rows do NOT nest inside rows.** The shape is
//!   `section -> (optional dynamic-key map) -> row`. A walker that models
//!   row-in-row is modelling something that does not exist.
//! * **An object carrying a string `id` IS a row.** The minted-prefix set is a
//!   literal array in dd that has already grown and will grow again, so the
//!   prefix is metadata and never the gate. An unknown prefix indexes normally.

use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt;

/// Separator between a ddoc's path and its address trail. Exactly one per
/// address; the bare form (`#section/id`) omits the path and means "this
/// document", which survives a rename.
pub const DDOC_ADDRESS_SEPARATOR: char = '#';

/// Filename suffix that makes a file a ddoc source. An exact suffix test —
/// dd's own detection — never content sniffing.
pub const DDOC_SOURCE_SUFFIX: &str = ".dd.json";

/// Filename suffix of the generated sibling.
pub const DDOC_GENERATED_SUFFIX: &str = ".dd.md";

/// First line of every generated sibling. Maintained in dd as a drift-gate key
/// (renaming it and regenerating the corpus must happen in one commit), which
/// is what makes it sound to lean on.
pub const DDOC_GENERATED_BANNER: &str =
    "<!-- GENERATED by `ddocs build` — do not hand-edit; regenerate from the .dd.json. -->";

/// How a row's embedded text was chosen.
///
/// Carried as DATA on every row, deliberately: a degraded parse that renders
/// identically to a healthy one is how a corpus silently disagrees with
/// itself. "We degraded" must be queryable, not invisible.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EmbedBasis {
    /// The schema resolved and declared which fields are prose.
    SchemaDeclared,
    /// No schema was resolvable; the documented JSON-shape fallback was used.
    Fallback,
}

/// A row's completion state as *derived from its assertions*, which is a
/// SEPARATE CLAIM from the row's stored `state` field.
///
/// dd does not reconcile the two: a task can read `checked` over an
/// all-`unchecked` assertion list and validation raises nothing. When they
/// disagree, this is the one to believe — it is computed from rows.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct DerivedState {
    /// True when nothing is outstanding.
    pub complete: bool,
    /// Ids whose state falls outside the gate-terminal set, in input order.
    pub incomplete: Vec<String>,
}

/// One typed edge leaving a row, as dd resolved it.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DdocRel {
    /// The relation. dd's built-in set (`pressure`, `proven_by`, `satisfies`,
    /// `derives`, `ref`) is frozen but the NAMESPACE IS OPEN: an unknown
    /// relation is still a first-class link and must be walked, never dropped.
    /// Built-ins buy extra meaning; they do not gate traversal.
    pub rel: String,
    /// The address this edge points at.
    pub target: String,
    /// `document` or `file`. **`file` edges do not exist on dd `main` yet** —
    /// they arrive with dd PR #12, open as of 2026-08-28 — so an absent value
    /// must default to `document` rather than erroring or dropping the edge.
    pub kind: String,
    /// JSONPath into the source document where the edge was declared.
    pub location: String,
}

impl DdocRel {
    /// The relation that carries a legal non-address sentinel.
    ///
    /// A `pressure` field may hold the literal `not-applicable`, meaning "no
    /// instrument checks this". It is not a path, not an id, and NOT a broken
    /// link — it is the queryable form of "nothing checks this". The exclusion
    /// is keyed on the RELATION, never on a field name.
    pub const PRESSURE: &'static str = "pressure";

    /// The sentinel itself.
    pub const NOT_APPLICABLE: &'static str = "not-applicable";

    /// Default edge kind, used when dd emits none.
    pub const KIND_DOCUMENT: &'static str = "document";

    /// Edge kind naming an ordinary repo file (dd PR #12).
    pub const KIND_FILE: &'static str = "file";

    /// Whether this edge is the "nothing checks this" sentinel rather than a
    /// link to anything. Keyed on the relation, per dd's own bug-and-fix.
    pub fn is_pressure_sentinel(&self) -> bool {
        self.rel == Self::PRESSURE && self.target == Self::NOT_APPLICABLE
    }

    /// Whether this edge names an ordinary repo file — the inverse-index half.
    pub fn is_file_edge(&self) -> bool {
        self.kind == Self::KIND_FILE
    }
}

/// The facts a schema declares, read out of `ddocs --json schema show` by the
/// imperative shell and handed to the pure parser.
///
/// Prose-ness is DECLARED, never inferred from a field name: dd's design rule
/// is that semantics live on the declaration. `text` is the prose type;
/// `string` is the catch-all that still carries real prose; everything else —
/// `state`, `enum`, `int`, `number`, `bool`, `link` — is metadata that dilutes
/// a vector and is never embedded.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct DdocSchemaFacts {
    /// Qualified `<pkg>/<name>` this describes.
    pub schema: String,
    /// Section name -> fields declared `text`. Embedded at full weight.
    pub prose_fields: BTreeMap<String, Vec<String>>,
    /// Section name -> fields declared `string`. Embedded, weighted lower.
    pub string_fields: BTreeMap<String, Vec<String>>,
    /// States that PASS a gate. Defaults to `checked ∪ human-skipped ∪ na`,
    /// but a schema may declare its own vocabulary — so "is this done?" means
    /// membership in THIS set, never string equality against `"checked"`.
    pub gate_terminal: BTreeSet<String>,
}

impl DdocSchemaFacts {
    /// Fields worth embedding for a section, prose first then catch-all.
    ///
    /// Returns `None` when the section is unknown to the schema, which the
    /// caller must treat as "fall back", not as "embed nothing".
    pub fn embeddable(&self, section: &str) -> Option<(&[String], &[String])> {
        let prose = self.prose_fields.get(section)?;
        let strings = self
            .string_fields
            .get(section)
            .map_or(&[][..], |fields| fields.as_slice());
        Some((prose.as_slice(), strings))
    }

    /// Whether a state passes the gate this schema declares.
    pub fn is_gate_terminal(&self, state: &str) -> bool {
        self.gate_terminal.contains(state)
    }
}

/// Everything flowspace3 knows about one ddoc row.
///
/// Boxed onto [`crate::Element`], so a code element pays one null pointer for
/// a document feature it never uses.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DdocMeta {
    /// dd's own citation, positional: `file#section/id`. Pastes straight into
    /// `ddocs get`.
    pub address: String,
    /// `dd.schema` verbatim; empty when the document declares none.
    pub schema: String,
    /// The parent trail — `["section", "<map key>"?, "id"]`. Carried so a row
    /// stays findable by its document's subject matter, which the row text
    /// alone usually lacks.
    pub trail: Vec<String>,
    /// Section the row lives in.
    pub section: String,
    /// The row's own id.
    pub id: String,
    /// The RAW minted prefix (`ac`, `tk`, ...), or `None` for an id that
    /// carries none. Never a closed enum: dd's prefix set grows.
    pub id_kind: Option<String>,
    /// The row's STORED state, verbatim. Never trusted on its own — see
    /// [`DdocMeta::derived_state`].
    pub state: Option<String>,
    /// Whether [`DdocMeta::state`] passes the schema's gate. `None` when no
    /// schema was resolvable.
    pub gate_terminal: Option<bool>,
    /// The state computed from this row's assertions. Believe this one.
    pub derived_state: Option<DerivedState>,
    /// `sections[meta].value.title`, where the document has one.
    pub doc_title: Option<String>,
    /// The document asked corpus-wide sweeps to skip it (`dd.sweep_exclude`).
    ///
    /// This excludes it from HEALTH REPORTING only. The document is indexed
    /// normally: a search tool that hides a document cannot be told apart from
    /// one where the document does not exist, and that is the worse failure.
    pub sweep_excluded: bool,
    /// How [`crate::Element::raw_text`] was chosen for this row.
    pub embed_basis: EmbedBasis,
    /// Outbound edges, attached by the shell. Empty from the parser alone.
    pub rels: Vec<DdocRel>,
    /// Validation findings. A document with a broken link is STILL A DDOC and
    /// still worth indexing — the finding rides as metadata and the query
    /// decides.
    pub findings: Vec<String>,
}

impl DdocMeta {
    /// A row as the pure parser can know it, before the shell enriches it.
    pub fn new(
        address: impl Into<String>,
        schema: impl Into<String>,
        trail: Vec<String>,
        embed_basis: EmbedBasis,
    ) -> Self {
        let section = trail.first().cloned().unwrap_or_default();
        let id = trail.last().cloned().unwrap_or_default();
        let id_kind = minted_prefix(&id).map(str::to_owned);
        DdocMeta {
            address: address.into(),
            schema: schema.into(),
            trail,
            section,
            id,
            id_kind,
            state: None,
            gate_terminal: None,
            derived_state: None,
            doc_title: None,
            sweep_excluded: false,
            embed_basis,
            rels: Vec::new(),
            findings: Vec::new(),
        }
    }

    /// The state a consumer should believe, and whether it was derived.
    ///
    /// Prefers the derived value; falls back to the stored one, labelled. A
    /// caller that shows only the stored value is authoritative about the
    /// wrong number.
    pub fn effective_state(&self) -> Option<(bool, bool)> {
        if let Some(derived) = &self.derived_state {
            return Some((derived.complete, true));
        }
        self.gate_terminal.map(|passes| (passes, false))
    }
}

/// The minted-id prefix of an id, if it has one.
///
/// dd mints `<prefix>-<four lowercase hex>`. This reads the prefix; it does not
/// judge it. An unrecognised prefix is a valid row.
pub fn minted_prefix(id: &str) -> Option<&str> {
    let (prefix, suffix) = id.split_once('-')?;
    if prefix.is_empty() || suffix.len() != 4 {
        return None;
    }
    if !suffix
        .bytes()
        .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit())
    {
        return None;
    }
    if !suffix.bytes().all(|b| b.is_ascii_hexdigit()) {
        return None;
    }
    Some(prefix)
}

/// Why an address could not be parsed.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum DdocAddressError {
    /// No `#`, so there is no trail to address.
    MissingSeparator,
    /// More than one `#`. The grammar allows exactly one.
    MultipleSeparators,
    /// The trail after `#` was empty.
    EmptyTrail,
    /// A trail segment was empty (`a//b`).
    EmptySegment,
}

impl fmt::Display for DdocAddressError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let text = match self {
            DdocAddressError::MissingSeparator => "ddoc address needs exactly one '#'",
            DdocAddressError::MultipleSeparators => "ddoc address has more than one '#'",
            DdocAddressError::EmptyTrail => "ddoc address has no trail after '#'",
            DdocAddressError::EmptySegment => "ddoc address has an empty trail segment",
        };
        f.write_str(text)
    }
}

impl std::error::Error for DdocAddressError {}

/// A dd address: `file#name/id/name/id…`.
///
/// The grammar is POSITIONAL — the first trail segment is always read as a
/// SECTION NAME. Ids are unique document-wide, but that does NOT make
/// `file#id` resolvable: dd answers `E450 declares no section <id>`. So a
/// single-segment trail addresses a section, never a row, and flowspace3 never
/// emits the short form.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DdocAddress {
    /// Repo-relative path, or empty for the bare `#section/id` form.
    pub file: String,
    /// Alternating names and ids, in order.
    pub trail: Vec<String>,
}

impl DdocAddress {
    /// Parse dd's address grammar.
    pub fn parse(text: &str) -> Result<Self, DdocAddressError> {
        let mut parts = text.splitn(2, DDOC_ADDRESS_SEPARATOR);
        let file = parts.next().unwrap_or_default();
        let trail = parts.next().ok_or(DdocAddressError::MissingSeparator)?;
        if trail.contains(DDOC_ADDRESS_SEPARATOR) {
            return Err(DdocAddressError::MultipleSeparators);
        }
        if trail.is_empty() {
            return Err(DdocAddressError::EmptyTrail);
        }
        let segments: Vec<String> = trail.split('/').map(str::to_owned).collect();
        if segments.iter().any(String::is_empty) {
            return Err(DdocAddressError::EmptySegment);
        }
        Ok(DdocAddress {
            file: file.to_owned(),
            trail: segments,
        })
    }

    /// Render back to dd's grammar. Round-trips [`DdocAddress::parse`].
    pub fn render(&self) -> String {
        let mut out = String::with_capacity(self.file.len() + 1 + self.trail.len() * 8);
        out.push_str(&self.file);
        out.push(DDOC_ADDRESS_SEPARATOR);
        for (index, segment) in self.trail.iter().enumerate() {
            if index > 0 {
                out.push('/');
            }
            out.push_str(segment);
        }
        out
    }

    /// The section this address is rooted in — always the first segment.
    pub fn section(&self) -> &str {
        self.trail.first().map_or("", String::as_str)
    }

    /// The addressed row's id, or `None` when the address names a section.
    ///
    /// A single-segment trail is a SECTION address. Reading it as an id is the
    /// mistake the positional grammar invites.
    pub fn row_id(&self) -> Option<&str> {
        if self.trail.len() < 2 {
            return None;
        }
        self.trail.last().map(String::as_str)
    }
}

impl fmt::Display for DdocAddress {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.render())
    }
}

/// Derive a completion state from a set of `(id, state)` entries.
///
/// **This is the ONLY place flowspace3 implements dd's derivation rule**, and
/// it is deliberately one function so that swapping it for a `ddocs --json
/// derive` call is a one-line change the day dd exposes one. dd computes this
/// in `src/core/derive.ts` (`deriveItems`/`deriveState`/`deriveRollup`) but
/// exposes it through neither its Node exports nor its CLI, so we must — with
/// dd's maintainer's agreement, and against their standing preference that we
/// should not have to.
///
/// The rule, verbatim: collect every state entry structurally; `incomplete` is
/// the ids whose state falls outside the gate-terminal set; `complete` is
/// `incomplete.is_empty()`.
///
/// An entry with NO state counts as incomplete. An unmeasured thing must never
/// render as a measured one, and `None` is the absence of a claim, not a claim
/// of completion.
///
/// `gate_terminal` comes from the row's schema and is never the hardcoded five
/// built-in states — a schema may declare its own vocabulary.
pub fn derive_state<'a>(
    entries: impl IntoIterator<Item = (&'a str, Option<&'a str>)>,
    gate_terminal: &BTreeSet<String>,
) -> DerivedState {
    let incomplete: Vec<String> = entries
        .into_iter()
        .filter(|(_, state)| !state.is_some_and(|state| gate_terminal.contains(state)))
        .map(|(id, _)| id.to_owned())
        .collect();
    DerivedState {
        complete: incomplete.is_empty(),
        incomplete,
    }
}

/// dd's default gate-terminal set, for a document whose schema declares none.
///
/// Present as a DEFAULT, not as a constant to compare against: reading the
/// schema is always correct, and hardcoding these five is the trap.
pub fn default_gate_terminal() -> BTreeSet<String> {
    ["checked", "human-skipped", "na"]
        .into_iter()
        .map(str::to_owned)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn gate(values: &[&str]) -> BTreeSet<String> {
        values.iter().map(|value| (*value).to_owned()).collect()
    }

    #[test]
    fn address_round_trips_a_row() {
        let text = "docs/plans/065/tasks.dd.json#tasks/tk-9f2a";
        let address = DdocAddress::parse(text).expect("parses");
        assert_eq!(address.file, "docs/plans/065/tasks.dd.json");
        assert_eq!(address.section(), "tasks");
        assert_eq!(address.row_id(), Some("tk-9f2a"));
        assert_eq!(address.render(), text);
    }

    #[test]
    fn address_round_trips_the_bare_form() {
        let text = "#done_when/tk-9f2a/dw-a9c4";
        let address = DdocAddress::parse(text).expect("parses");
        assert_eq!(address.file, "");
        assert_eq!(address.section(), "done_when");
        assert_eq!(address.trail, ["done_when", "tk-9f2a", "dw-a9c4"]);
        assert_eq!(address.row_id(), Some("dw-a9c4"));
        assert_eq!(address.render(), text);
    }

    #[test]
    fn single_segment_addresses_a_section_never_a_row() {
        // The grammar is positional: dd answers E450 "declares no section
        // ac-1a2b" for this shape. Reading it as an id is the trap.
        let address = DdocAddress::parse("plan.dd.json#ac-1a2b").expect("parses");
        assert_eq!(address.section(), "ac-1a2b");
        assert_eq!(address.row_id(), None);
    }

    #[test]
    fn address_rejects_malformed_input() {
        assert_eq!(
            DdocAddress::parse("plan.dd.json"),
            Err(DdocAddressError::MissingSeparator)
        );
        assert_eq!(
            DdocAddress::parse("plan.dd.json#a#b"),
            Err(DdocAddressError::MultipleSeparators)
        );
        assert_eq!(
            DdocAddress::parse("plan.dd.json#"),
            Err(DdocAddressError::EmptyTrail)
        );
        assert_eq!(
            DdocAddress::parse("plan.dd.json#tasks//tk-9f2a"),
            Err(DdocAddressError::EmptySegment)
        );
    }

    #[test]
    fn minted_prefix_reads_without_judging() {
        assert_eq!(minted_prefix("ac-1a2b"), Some("ac"));
        assert_eq!(minted_prefix("dw-a9c4"), Some("dw"));
        // An unregistered prefix is a VALID row: dd's prefix set has grown and
        // will grow again, so this must not be gated on a known list.
        assert_eq!(minted_prefix("zz-0001"), Some("zz"));
        assert_eq!(minted_prefix("custom-0001"), Some("custom"));
        // Not minted-shaped at all: still a row, just without a prefix.
        assert_eq!(minted_prefix("some-identifier"), None);
        assert_eq!(minted_prefix("plain"), None);
        assert_eq!(minted_prefix("ac-1A2B"), None);
    }

    #[test]
    fn derive_state_is_complete_when_every_entry_passes_the_gate() {
        let derived = derive_state(
            [("dw-0001", Some("checked")), ("dw-0002", Some("na"))],
            &gate(&["checked", "human-skipped", "na"]),
        );
        assert!(derived.complete);
        assert!(derived.incomplete.is_empty());
    }

    #[test]
    fn derive_state_names_every_open_id_in_order() {
        let derived = derive_state(
            [
                ("dw-0001", Some("checked")),
                ("dw-0002", Some("unchecked")),
                ("dw-0003", Some("blocked")),
            ],
            &gate(&["checked", "human-skipped", "na"]),
        );
        assert!(!derived.complete);
        assert_eq!(derived.incomplete, ["dw-0002", "dw-0003"]);
    }

    #[test]
    fn derive_state_counts_a_missing_state_as_incomplete() {
        // An unmeasured thing must never render as a measured one.
        let derived = derive_state([("dw-0001", None)], &gate(&["checked"]));
        assert!(!derived.complete);
        assert_eq!(derived.incomplete, ["dw-0001"]);
    }

    #[test]
    fn derive_state_honours_a_custom_vocabulary() {
        // A schema may declare its own gate_terminal set. Hardcoding dd's five
        // built-ins would call this incomplete.
        let derived = derive_state(
            [("tk-0001", Some("shipped")), ("tk-0002", Some("waived"))],
            &gate(&["shipped", "waived"]),
        );
        assert!(derived.complete);

        // ...and "checked" is NOT terminal under that vocabulary.
        let derived = derive_state([("tk-0003", Some("checked"))], &gate(&["shipped"]));
        assert!(!derived.complete);
        assert_eq!(derived.incomplete, ["tk-0003"]);
    }

    #[test]
    fn derive_state_over_no_entries_is_complete() {
        let derived = derive_state([], &default_gate_terminal());
        assert!(derived.complete);
    }

    #[test]
    fn effective_state_prefers_the_derived_claim_over_the_stored_one() {
        let mut meta = DdocMeta::new(
            "plan.dd.json#tasks/tk-0001",
            "builder/plan",
            vec!["tasks".into(), "tk-0001".into()],
            EmbedBasis::SchemaDeclared,
        );
        // The trap: stored says done, the assertions say otherwise. dd does not
        // reconcile these and validation raises nothing.
        meta.state = Some("checked".into());
        meta.gate_terminal = Some(true);
        meta.derived_state = Some(DerivedState {
            complete: false,
            incomplete: vec!["dw-0002".into()],
        });

        assert_eq!(meta.effective_state(), Some((false, true)));
        // The stored claim is still available, and still labelled as stored.
        assert_eq!(meta.state.as_deref(), Some("checked"));
    }

    #[test]
    fn effective_state_falls_back_to_the_stored_claim_and_says_so() {
        let mut meta = DdocMeta::new(
            "plan.dd.json#tasks/tk-0001",
            "builder/plan",
            vec!["tasks".into(), "tk-0001".into()],
            EmbedBasis::SchemaDeclared,
        );
        meta.gate_terminal = Some(true);
        assert_eq!(meta.effective_state(), Some((true, false)));
    }

    #[test]
    fn meta_reads_section_id_and_prefix_from_the_trail() {
        let meta = DdocMeta::new(
            "plan.dd.json#done_when/tk-9f2a/dw-a9c4",
            "builder/plan",
            vec!["done_when".into(), "tk-9f2a".into(), "dw-a9c4".into()],
            EmbedBasis::Fallback,
        );
        assert_eq!(meta.section, "done_when");
        assert_eq!(meta.id, "dw-a9c4");
        assert_eq!(meta.id_kind.as_deref(), Some("dw"));
        assert_eq!(meta.embed_basis, EmbedBasis::Fallback);
        assert!(!meta.sweep_excluded);
    }

    #[test]
    fn pressure_sentinel_is_keyed_on_the_relation_not_a_field_name() {
        let sentinel = DdocRel {
            rel: DdocRel::PRESSURE.into(),
            target: DdocRel::NOT_APPLICABLE.into(),
            kind: DdocRel::KIND_DOCUMENT.into(),
            location: "$.sections[tasks].value[0].pressure".into(),
        };
        assert!(sentinel.is_pressure_sentinel());

        // The same literal under a different relation is NOT the sentinel.
        let other = DdocRel {
            rel: "ref".into(),
            target: DdocRel::NOT_APPLICABLE.into(),
            ..sentinel.clone()
        };
        assert!(!other.is_pressure_sentinel());
    }

    #[test]
    fn file_edges_are_recognised_and_document_edges_are_not() {
        let file_edge = DdocRel {
            rel: "ref".into(),
            target: "crates/core/src/ddoc.rs".into(),
            kind: DdocRel::KIND_FILE.into(),
            location: "$.sections[tasks].value[0].touches".into(),
        };
        assert!(file_edge.is_file_edge());

        let document_edge = DdocRel {
            kind: DdocRel::KIND_DOCUMENT.into(),
            ..file_edge.clone()
        };
        assert!(!document_edge.is_file_edge());
    }

    #[test]
    fn schema_facts_answer_embeddable_fields_per_section() {
        let mut facts = DdocSchemaFacts {
            schema: "builder/plan".into(),
            ..DdocSchemaFacts::default()
        };
        facts
            .prose_fields
            .insert("tasks".into(), vec!["title".into(), "success".into()]);
        facts
            .string_fields
            .insert("tasks".into(), vec!["notes".into()]);

        let (prose, strings) = facts.embeddable("tasks").expect("known section");
        assert_eq!(prose, ["title", "success"]);
        assert_eq!(strings, ["notes"]);

        // An unknown section means "fall back", not "embed nothing".
        assert!(facts.embeddable("phases").is_none());
    }

    #[test]
    fn gate_terminal_membership_comes_from_the_schema() {
        let facts = DdocSchemaFacts {
            schema: "custom/plan".into(),
            gate_terminal: gate(&["shipped"]),
            ..DdocSchemaFacts::default()
        };
        assert!(facts.is_gate_terminal("shipped"));
        assert!(!facts.is_gate_terminal("checked"));
    }
}
